#!/usr/bin/python3.9

# Filename: Random_Password_Generator
	
print('        Random Password Generator')
print('         Made by Rokaya Muhammad')
Name = input('Your Name: ')
print("Hello,",Name,"!")
import random
import string

def get_string(letters_count, digits_count):
    letters = ''.join((random.choice(string.ascii_letters) for i in range(letters_count)))
    digits = ''.join((random.choice(string.digits) for i in range(digits_count)))

    # Convert resultant string to list and shuffle it to mix letters and digits
    sample_list = list(letters + digits)
    random.shuffle(sample_list)
    # convert list to string
    final_string = ''.join(sample_list)
    print('Your password with', letters_count, 'letters', 'and', digits_count, 'digits', 'is:', final_string)

get_string(5, 3)
# Output get_string(5, 3)

get_string(6, 2)
# Output Random string with 6 letters and 2 digits is: 7DeOCm5t
print('Checkout this two too!')
import random
import string

def get_string(letters_count, digits_count):
    letters = ''.join((random.choice(string.ascii_letters) for i in range(letters_count)))
    digits = ''.join((random.choice(string.digits) for i in range(digits_count)))

    # Convert resultant string to list and shuffle it to mix letters and digits
    sample_list = list(letters + digits)
    random.shuffle(sample_list)
    # convert list to string
    final_string = ''.join(sample_list)
    print('Your password with', letters_count, 'letters', 'and', digits_count, 'digits', 'is:', final_string)

get_string(5, 3)
# Output get_string(5, 3)

get_string(6, 2)
# Output Random string with 6 letters and 2 digits is: 7DeOCm5t
print('Bye,' ,Name)
